version: "3.7"

services:
  proxy:
    build: .
    image: filterproxy
    networks:
      - filterproxy_network
    expose:
      - "8080"
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - ./static:/usr/share/nginx/static:ro
      - ./config/nginx:/etc/nginx:ro
      - ./log:/var/log/
    networks:
      - filterproxy_network
    ports:
      - "8080:80"

networks:
  filterproxy_network: